title: HRI Conference Deadlines 
description: Countdowns to HRI related conference deadlines
author: Zhi Tan
author_website: https://zhi.fyi

domain: "hrideadlin.es"
baseurl: ""

github_username: xiangzhi
github_repo: hri-deadlines

markdown: kramdown
ga_id: UA-36274081-2

#include: ['_pages']