title: HRI Conference Deadlines 
description: Countdowns to HRI related conference deadlines
author: Zhi Tan

domain: "hrideadlines.zhi.fyi"
baseurl: ""

github_username: xiangzhi
github_repo: hri-deadlines

markdown: kramdown
ga_id: UA-36274081-2

#include: ['_pages']